story/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
]

storyline/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static

import story.urls

urlpatterns = [
    url(r'^story/', include(story.urls)),
    url(r'^admin/', include(admin.site.urls)),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

story/models.py
from django.db import models

class Story(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name

class Page(models.Model):
    story = models.ForeignKey(Story)
    page_number = models.IntegerField()

    image = models.ImageField()
    music = models.FileField()

    def __str__(self):
        return "Page %d of %s" % (self.page_number, self.story)

story/views.py
from .models import Story

from django.views import generic

class IndexView(generic.ListView):
    template_name = 'index.html'
    model = Story

class DetailView(generic.DetailView):
    template_name = 'story.html'
    model = Story

story/templates/index.html
{% load staticfiles %}
<!doctype html>
<html lang="en">

	<head>
		<meta charset="utf-8">

		<title>Verhalen</title>

		<meta name="apple-mobile-web-app-capable" content="yes" />
		<meta name="apple-mobile-web-app-status-bar-style" content="black-translucent" />

		<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">

		<!--[if lt IE 9]>
    <script src="{% static "lib/js/html5shiv.js" %}"></script>
		<![endif]-->
	</head>

	<body>
    <ul>
    {% for story in story_list %}
      <li><a href="{% url 'detail' story.id %}">{{ story.name }}</a></li>
    {% endfor %}
    </ul>
	</body>
</html>

story/templates/story.html
{% load staticfiles %}
<!doctype html>
<html lang="en">

	<head>
		<meta charset="utf-8">

    <title>{{ story.name }}</title>

		<meta name="apple-mobile-web-app-capable" content="yes" />
		<meta name="apple-mobile-web-app-status-bar-style" content="black-translucent" />

		<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">

    <link rel="stylesheet" href="{% static "css/reveal.css" %}">
    <link rel="stylesheet" href="{% static "css/theme/black.css" %}" id="theme">

		<!-- Code syntax highlighting -->
    <link rel="stylesheet" href="{% static "lib/css/zenburn.css" %}">

		<!-- Printing and PDF exports -->
		<script>
			var link = document.createElement( 'link' );
			link.rel = 'stylesheet';
			link.type = 'text/css';
      link.href = window.location.search.match( /print-pdf/gi ) ? '{% static "css/print/pdf.css" %}' : '{% static "css/print/paper.css" %}';
			document.getElementsByTagName( 'head' )[0].appendChild( link );
		</script>

		<!--[if lt IE 9]>
    <script src="{% static "lib/js/html5shiv.js" %}"></script>
		<![endif]-->
	</head>

	<body>

		<div class="reveal">

			<!-- Any section element inside of this container is displayed as a slide -->
			<div class="slides">
      {% for page in story.page_set.all %}
        <section data-background="{{ page.image.url }}" style="bottom:0;">
          <audio data-autoplay src="{{ page.music.url }}" controls></audio>
        </section>
      {% endfor %}
			</div>

		</div>

    <script src="{% static "lib/js/head.min.js" %}"></script>
    <script src="{% static "js/reveal.js" %}"></script>

		<script>

			// Full list of configuration options available at:
			// https://github.com/hakimel/reveal.js#configuration
			Reveal.initialize({
        backgroundTransition: "slide",
        center: false,
			});

		</script>

	</body>
</html>